'use client';
import { useEffect,useState } from 'react';
import { Tabs,TabsContent,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
type Appointment={id:number;name:string;email:string;reason:string;availability:string;status:string;createdAt:string};
type Member={id:number;name:string;role:string;bio:string};
type Data={setup?:boolean;appointments?:Appointment[];team?:Member[];settings?:Record<string,string>;error?:string};
const labels:Record<string,string>={new:'Nouvelle',confirmed:'Confirmée',completed:'Terminée',cancelled:'Annulée'};
export default function Admin(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[member,setMember]=useState<Partial<Member>>({}),[settings,setSettings]=useState<Record<string,string>>({});
 async function load(){try{const r=await fetch('/api/admin',{cache:'no-store'});const j=await r.json() as Data;setData(j);if(j.settings)setSettings(j.settings);if(!r.ok)setError(j.error||'Accès indisponible.');}catch{setError('Connexion indisponible.')}}
 useEffect(()=>{void load()},[]);
 async function act(action:string,values:Record<string,unknown>={}){setBusy(true);setError('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...values})});const j=await r.json() as {error?:string};if(!r.ok)throw new Error(j.error||'Enregistrement impossible.');await load();return true}catch(e){setError(e instanceof Error?e.message:'Erreur.');return false}finally{setBusy(false)}}
 return <div className="min-h-screen bg-[#f5fafc] text-[#173b49]"><header className="sticky top-0 z-20 border-b border-[#dceaf0] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4"><div><div className="text-xl font-bold tracking-tight">✧ Cabinet Dentaire</div><div className="text-xs text-[#6c8a96]">Espace administration</div></div><a className="rounded-full border border-[#cde4ec] px-4 py-2 text-sm font-semibold hover:bg-[#eaf7fc]" href="/landing.html">Voir le site</a></div></header>
 <main className="mx-auto max-w-7xl px-5 py-10"><div className="mb-9"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#408da3]">Tableau de bord</p><h1 className="mt-2 text-3xl font-bold tracking-tight md:text-4xl">Gérer le cabinet</h1><p className="mt-2 text-[#6c8490]">Rendez-vous, équipe et informations publiques au même endroit.</p></div>
 {error&&<div role="alert" className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}
 {!data&&!error&&<p>Chargement…</p>}
 {data?.setup&&<div className="max-w-xl rounded-3xl border border-[#dceaf0] bg-white p-8 shadow-sm"><h2 className="text-xl font-bold">Activer l’administration</h2><p className="my-4 leading-7 text-[#637d88]">Le premier propriétaire connecté à ce site privé devient administrateur. Activez cet espace avant d’ouvrir le site aux visiteurs.</p><Button disabled={busy} onClick={()=>void act('bootstrap')}>Activer mon espace</Button></div>}
 {data&&!data.setup&&!data.error&&<Tabs defaultValue="appointments" className="gap-6"><TabsList className="h-auto flex-wrap bg-[#e8f4f8] p-1"><TabsTrigger value="appointments">Rendez-vous ({data.appointments?.length||0})</TabsTrigger><TabsTrigger value="team">Équipe</TabsTrigger><TabsTrigger value="settings">Informations</TabsTrigger></TabsList>
 <TabsContent value="appointments"><div className="space-y-3">{!data.appointments?.length&&<div className="rounded-2xl bg-white p-10 text-center text-[#6c8490]">Aucune demande reçue pour le moment.</div>}{data.appointments?.map(a=><article key={a.id} className="grid gap-4 rounded-2xl border border-[#e0ecf0] bg-white p-5 shadow-sm md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-3"><h3 className="font-bold">{a.name}</h3><span className="rounded-full bg-[#eaf7fc] px-3 py-1 text-xs font-semibold text-[#216c81]">{labels[a.status]||a.status}</span></div><p className="mt-2 text-sm text-[#607b86]">{a.reason} · {a.email}</p><p className="mt-1 text-sm text-[#607b86]">Disponibilités : {a.availability||'Non précisées'} · {new Date(a.createdAt+'Z').toLocaleDateString('fr-FR')}</p></div><select aria-label={'Statut de '+a.name} className="rounded-xl border border-[#d4e5eb] bg-white px-3 py-2 text-sm" value={a.status} disabled={busy} onChange={e=>void act('status',{id:a.id,status:e.target.value})}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></article>)}</div></TabsContent>
 <TabsContent value="team"><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{!data.team?.length&&<div className="rounded-2xl bg-white p-8 text-[#607b86]">Ajoutez les membres de l’équipe pour les afficher sur le site.</div>}{data.team?.map(t=><div key={t.id} className="flex items-start justify-between gap-4 rounded-2xl border border-[#e0ecf0] bg-white p-5"><div><h3 className="font-bold">{t.name}</h3><p className="text-sm font-semibold text-[#3d8ba1]">{t.role}</p><p className="mt-2 text-sm text-[#607b86]">{t.bio}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>setMember(t)}>Modifier</Button><Button variant="outline" size="sm" disabled={busy} onClick={()=>{if(confirm('Supprimer ce membre ?'))void act('team-delete',{id:t.id})}}>Supprimer</Button></div></div>)}</div><form className="h-fit space-y-4 rounded-2xl border border-[#e0ecf0] bg-white p-6" onSubmit={async e=>{e.preventDefault();if(await act('team-save',member))setMember({})}}><h2 className="font-bold">{member.id?'Modifier un membre':'Ajouter un membre'}</h2><label className="block text-sm font-semibold">Nom<input required maxLength={100} className="mt-1 w-full rounded-xl border border-[#d4e5eb] p-3" value={member.name||''} onChange={e=>setMember({...member,name:e.target.value})}/></label><label className="block text-sm font-semibold">Fonction<input required maxLength={100} className="mt-1 w-full rounded-xl border border-[#d4e5eb] p-3" value={member.role||''} onChange={e=>setMember({...member,role:e.target.value})}/></label><label className="block text-sm font-semibold">Présentation<textarea maxLength={500} rows={4} className="mt-1 w-full rounded-xl border border-[#d4e5eb] p-3" value={member.bio||''} onChange={e=>setMember({...member,bio:e.target.value})}/></label><div className="flex gap-2"><Button disabled={busy} type="submit">Enregistrer</Button>{member.id&&<Button type="button" variant="outline" onClick={()=>setMember({})}>Annuler</Button>}</div></form></div></TabsContent>
 <TabsContent value="settings"><form className="max-w-2xl space-y-5 rounded-2xl border border-[#e0ecf0] bg-white p-6 md:p-8" onSubmit={e=>{e.preventDefault();void act('settings',settings)}}><h2 className="text-xl font-bold">Informations du cabinet</h2><p className="text-sm text-[#607b86]">Ces informations remplacent les textes provisoires du site.</p>{([['cabinetName','Nom du cabinet'],['tagline','Phrase d’accueil'],['phone','Téléphone'],['email','E-mail'],['address','Adresse'],['hours','Horaires']] as const).map(([key,label])=><label key={key} className="block text-sm font-semibold">{label}<input maxLength={300} className="mt-1 w-full rounded-xl border border-[#d4e5eb] p-3" value={settings[key]||''} onChange={e=>setSettings({...settings,[key]:e.target.value})}/></label>)}<Button disabled={busy} type="submit">Enregistrer les informations</Button></form></TabsContent></Tabs>}
 </main></div>
}
