'use client';
import { useEffect,useState } from 'react';
import { Tabs,TabsContent,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
type Appointment={id:number;name:string;email:string;reason:string;availability:string;scheduledDate:string|null;slotTime:string|null;status:string;createdAt:string};
type Member={id:number;name:string;role:string;bio:string};
type Hour={weekday:number;isOpen:number;startTime:string;endTime:string};
type Block={id:number;date:string;time:string;note:string};
type Employee={id:number;name:string;email:string;role:string;active:number};
type Data={setup?:boolean;role?:string;appointments?:Appointment[];team?:Member[];settings?:Record<string,string>;hours?:Hour[];blocks?:Block[];employees?:Employee[];error?:string};
const labels:Record<string,string>={new:'En attente',confirmed:'Accepté',completed:'Terminé',cancelled:'Refusé / annulé'};
const dayNames=['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'];
const employeeRoles:Record<string,string>={manager:'Responsable',reception:'Accueil et rendez-vous',content:'Équipe et informations'};
const timeOptions=Array.from({length:25},(_,i)=>`${String(8+Math.floor(i/2)).padStart(2,'0')}:${i%2?'30':'00'}`);
const today=new Date().toISOString().slice(0,10),maxDate=new Date(Date.now()+90*86400000).toISOString().slice(0,10);
const input='mt-1 w-full rounded-xl border border-[#d4e5eb] bg-white p-3 text-[#173b49] focus:border-[#4e9db2] focus:outline-none';
export default function Admin(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[member,setMember]=useState<Partial<Member>>({}),[employee,setEmployee]=useState<Partial<Employee>>({role:'reception',active:1}),[settings,setSettings]=useState<Record<string,string>>({}),[hours,setHours]=useState<Hour[]>([]),[block,setBlock]=useState({date:today,time:'09:00',note:''});
 async function load(){try{const r=await fetch('/api/admin',{cache:'no-store'});const j=await r.json() as Data;setData(j);if(j.settings)setSettings(j.settings);if(j.hours?.length)setHours(j.hours);if(!r.ok)setError(j.error||'Accès indisponible.');else setError('')}catch{setError('Connexion indisponible.')}}
 useEffect(()=>{void load()},[]);
 async function act(action:string,values:Record<string,unknown>={}){setBusy(true);setError('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...values})});const j=await r.json() as {error?:string};if(!r.ok)throw new Error(j.error||'Enregistrement impossible.');await load();return true}catch(e){setError(e instanceof Error?e.message:'Erreur.');return false}finally{setBusy(false)}}
 const canAppointments=['owner','manager','reception'].includes(data?.role||''),canContent=['owner','manager','content'].includes(data?.role||''),isOwner=data?.role==='owner';
 const tab=canAppointments?'appointments':'team';
 return <div className="min-h-screen bg-[#f5fafc] text-[#173b49]"><header className="sticky top-0 z-20 border-b border-[#dceaf0] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4"><div><div className="text-xl font-bold tracking-tight">✧ Cabinet Dentaire</div><div className="text-xs text-[#6c8a96]">Espace administration</div></div><a className="rounded-full border border-[#cde4ec] px-4 py-2 text-sm font-semibold hover:bg-[#eaf7fc]" href="/landing.html">Voir le site</a></div></header>
 <main className="mx-auto max-w-7xl px-5 py-10"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#408da3]">Tableau de bord</p><h1 className="mt-2 text-3xl font-bold tracking-tight md:text-4xl">Gérer le cabinet</h1><p className="mt-2 text-[#6c8490]">Rendez-vous, disponibilités et équipe.</p></div>
 {error&&<div role="alert" className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}
 {!data&&!error&&<p>Chargement…</p>}
 {data?.setup&&<div className="max-w-xl rounded-3xl border border-[#dceaf0] bg-white p-8 shadow-sm"><h2 className="text-xl font-bold">Activer l’administration</h2><p className="my-4 leading-7 text-[#637d88]">Le premier propriétaire connecté à ce site privé devient administrateur. Activez cet espace avant d’ouvrir le site aux visiteurs.</p><Button disabled={busy} onClick={()=>void act('bootstrap')}>Activer mon espace</Button></div>}
 {data?.role&&<Tabs defaultValue={tab} className="gap-6"><TabsList className="h-auto flex-wrap bg-[#e8f4f8] p-1">{canAppointments&&<><TabsTrigger value="appointments">Rendez-vous ({data.appointments?.length||0})</TabsTrigger><TabsTrigger value="calendar">Calendrier</TabsTrigger></>}{canContent&&<><TabsTrigger value="team">Équipe</TabsTrigger><TabsTrigger value="settings">Informations</TabsTrigger></>}{isOwner&&<TabsTrigger value="employees">Employés</TabsTrigger>}</TabsList>
 {canAppointments&&<><TabsContent value="appointments"><div className="space-y-3">{!data.appointments?.length&&<div className="rounded-2xl bg-white p-10 text-center text-[#6c8490]">Aucune demande reçue pour le moment.</div>}{data.appointments?.map(a=><article key={a.id} className="grid gap-4 rounded-2xl border border-[#e0ecf0] bg-white p-5 shadow-sm md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-3"><h3 className="font-bold">{a.name}</h3><span className="rounded-full bg-[#eaf7fc] px-3 py-1 text-xs font-semibold text-[#216c81]">{labels[a.status]||a.status}</span></div><p className="mt-2 text-sm text-[#607b86]">{a.reason} · {a.email}</p><p className="mt-1 text-sm font-semibold text-[#3b7f92]">{a.scheduledDate&&a.slotTime?`${a.scheduledDate} à ${a.slotTime}`:'Ancienne demande sans créneau sélectionné'}</p><p className="mt-1 text-xs text-[#7f97a1]">Demande reçue le {new Date(a.createdAt+'Z').toLocaleDateString('fr-FR')}</p></div><select aria-label={'Statut de '+a.name} className="rounded-xl border border-[#d4e5eb] bg-white px-3 py-2 text-sm" value={a.status} disabled={busy} onChange={e=>void act('status',{id:a.id,status:e.target.value})}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></article>)}</div></TabsContent>
 <TabsContent value="calendar"><div className="grid gap-6 xl:grid-cols-[1fr_390px]"><div className="space-y-6"><section className="rounded-2xl border border-[#e0ecf0] bg-white p-6"><h2 className="text-xl font-bold">Horaires habituels</h2><p className="my-2 text-sm text-[#607b86]">Les visiteurs verront ces créneaux par pas de 30 minutes. Fuseau horaire du cabinet : Abidjan (GMT).</p><div className="mt-5 space-y-2">{hours.map(h=><div key={h.weekday} className="grid grid-cols-[110px_1fr_1fr] items-center gap-3 rounded-xl bg-[#f6fbfd] p-3 sm:grid-cols-[130px_65px_1fr_1fr]"><strong className="text-sm">{dayNames[h.weekday]}</strong><label className="col-span-2 flex items-center gap-2 text-xs sm:col-span-1"><input type="checkbox" checked={!!h.isOpen} onChange={e=>setHours(hours.map(x=>x.weekday===h.weekday?{...x,isOpen:e.target.checked?1:0}:x))}/> Ouvert</label><select aria-label={'Début '+dayNames[h.weekday]} className="rounded-lg border border-[#d4e5eb] bg-white p-2 text-sm" value={h.startTime} onChange={e=>setHours(hours.map(x=>x.weekday===h.weekday?{...x,startTime:e.target.value}:x))}>{timeOptions.slice(0,-1).map(t=><option key={t}>{t}</option>)}</select><select aria-label={'Fin '+dayNames[h.weekday]} className="rounded-lg border border-[#d4e5eb] bg-white p-2 text-sm" value={h.endTime} onChange={e=>setHours(hours.map(x=>x.weekday===h.weekday?{...x,endTime:e.target.value}:x))}>{timeOptions.slice(1).map(t=><option key={t}>{t}</option>)}</select></div>)}</div><Button className="mt-5" disabled={busy} onClick={()=>void act('hours',{hours})}>Enregistrer les horaires</Button></section>
 <section className="rounded-2xl border border-[#e0ecf0] bg-white p-6"><h2 className="text-xl font-bold">Créneaux occupés</h2><p className="mt-2 text-sm text-[#607b86]">Ajoutez une absence ou une heure indisponible. Les rendez-vous acceptés sont bloqués automatiquement.</p><div className="mt-5 space-y-2">{!data.blocks?.length&&<p className="text-sm text-[#7b939e]">Aucun créneau bloqué manuellement.</p>}{data.blocks?.map(b=><div key={b.id} className="flex items-center justify-between gap-3 rounded-xl bg-[#f5fafc] px-4 py-3"><div><strong className="text-sm">{b.date} · {b.time}</strong>{b.note&&<p className="text-xs text-[#67828e]">{b.note}</p>}</div><Button variant="outline" size="sm" disabled={busy} onClick={()=>void act('block-delete',{id:b.id})}>Libérer</Button></div>)}</div></section></div>
 <form className="h-fit space-y-4 rounded-2xl border border-[#e0ecf0] bg-white p-6" onSubmit={async e=>{e.preventDefault();if(await act('block-add',block))setBlock({...block,note:''})}}><h2 className="font-bold">Bloquer un créneau</h2><label className="block text-sm font-semibold">Date<input type="date" min={today} max={maxDate} required className={input} value={block.date} onChange={e=>setBlock({...block,date:e.target.value})}/></label><label className="block text-sm font-semibold">Heure<select className={input} value={block.time} onChange={e=>setBlock({...block,time:e.target.value})}>{timeOptions.map(t=><option key={t}>{t}</option>)}</select></label><label className="block text-sm font-semibold">Note interne<input maxLength={120} className={input} placeholder="Ex. formation, absence" value={block.note} onChange={e=>setBlock({...block,note:e.target.value})}/></label><Button disabled={busy} type="submit">Bloquer</Button></form></div></TabsContent></>}
 {canContent&&<><TabsContent value="team"><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{!data.team?.length&&<div className="rounded-2xl bg-white p-8 text-[#607b86]">Ajoutez les membres de l’équipe pour les afficher sur le site.</div>}{data.team?.map(t=><div key={t.id} className="flex items-start justify-between gap-4 rounded-2xl border border-[#e0ecf0] bg-white p-5"><div><h3 className="font-bold">{t.name}</h3><p className="text-sm font-semibold text-[#3d8ba1]">{t.role}</p><p className="mt-2 text-sm text-[#607b86]">{t.bio}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>setMember(t)}>Modifier</Button><Button variant="outline" size="sm" disabled={busy} onClick={()=>{if(confirm('Supprimer ce membre ?'))void act('team-delete',{id:t.id})}}>Supprimer</Button></div></div>)}</div><form className="h-fit space-y-4 rounded-2xl border border-[#e0ecf0] bg-white p-6" onSubmit={async e=>{e.preventDefault();if(await act('team-save',member))setMember({})}}><h2 className="font-bold">{member.id?'Modifier un membre':'Ajouter un membre'}</h2><label className="block text-sm font-semibold">Nom<input required maxLength={100} className={input} value={member.name||''} onChange={e=>setMember({...member,name:e.target.value})}/></label><label className="block text-sm font-semibold">Fonction<input required maxLength={100} className={input} value={member.role||''} onChange={e=>setMember({...member,role:e.target.value})}/></label><label className="block text-sm font-semibold">Présentation<textarea maxLength={500} rows={4} className={input} value={member.bio||''} onChange={e=>setMember({...member,bio:e.target.value})}/></label><div className="flex gap-2"><Button disabled={busy} type="submit">Enregistrer</Button>{member.id&&<Button type="button" variant="outline" onClick={()=>setMember({})}>Annuler</Button>}</div></form></div></TabsContent>
 <TabsContent value="settings"><form className="max-w-2xl space-y-5 rounded-2xl border border-[#e0ecf0] bg-white p-6 md:p-8" onSubmit={e=>{e.preventDefault();void act('settings',settings)}}><h2 className="text-xl font-bold">Informations du cabinet</h2>{([['cabinetName','Nom du cabinet'],['tagline','Phrase d’accueil'],['phone','Téléphone'],['email','E-mail'],['address','Adresse'],['hours','Horaires affichés']] as const).map(([key,label])=><label key={key} className="block text-sm font-semibold">{label}<input maxLength={300} className={input} value={settings[key]||''} onChange={e=>setSettings({...settings,[key]:e.target.value})}/></label>)}<Button disabled={busy} type="submit">Enregistrer les informations</Button></form></TabsContent></>}
 {isOwner&&<TabsContent value="employees"><div className="grid gap-6 lg:grid-cols-[1fr_390px]"><div className="space-y-3"><p className="text-sm text-[#607b86]">Un employé accède à ses fonctions avec le compte ChatGPT correspondant à son adresse e-mail. Donnez-lui aussi accès au Site dans les réglages de partage.</p>{!data.employees?.length&&<div className="rounded-2xl bg-white p-8 text-[#607b86]">Aucun employé ajouté.</div>}{data.employees?.map(staff=><div key={staff.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-[#e0ecf0] bg-white p-5"><div><h3 className="font-bold">{staff.name} {!staff.active&&<span className="text-xs text-[#a46b6b]">(désactivé)</span>}</h3><p className="text-sm text-[#607b86]">{staff.email} · {employeeRoles[staff.role]}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>setEmployee(staff)}>Modifier</Button><Button variant="outline" size="sm" disabled={busy} onClick={()=>{if(confirm('Supprimer cet accès ?'))void act('employee-delete',{id:staff.id})}}>Supprimer</Button></div></div>)}</div><form className="h-fit space-y-4 rounded-2xl border border-[#e0ecf0] bg-white p-6" onSubmit={async e=>{e.preventDefault();if(await act('employee-save',{...employee,active:!!employee.active}))setEmployee({role:'reception',active:1})}}><h2 className="font-bold">{employee.id?'Modifier un accès':'Créer un accès employé'}</h2><label className="block text-sm font-semibold">Nom<input required maxLength={100} className={input} value={employee.name||''} onChange={e=>setEmployee({...employee,name:e.target.value})}/></label><label className="block text-sm font-semibold">E-mail du compte<input required type="email" maxLength={180} className={input} value={employee.email||''} onChange={e=>setEmployee({...employee,email:e.target.value})}/></label><label className="block text-sm font-semibold">Droits<select className={input} value={employee.role||'reception'} onChange={e=>setEmployee({...employee,role:e.target.value})}>{Object.entries(employeeRoles).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!employee.active} onChange={e=>setEmployee({...employee,active:e.target.checked?1:0})}/> Compte actif</label><div className="flex gap-2"><Button disabled={busy} type="submit">Enregistrer l’accès</Button>{employee.id&&<Button type="button" variant="outline" onClick={()=>setEmployee({role:'reception',active:1})}>Annuler</Button>}</div></form></div></TabsContent>}
 </Tabs>}
 </main></div>
}
